dependencies:
  color_tft:
    url: github.com/toitware/toit-color-tft
    version: ^1.3.0
  font_x11_adobe:
    url: github.com/toitlang/pkg-font-x11-adobe
    version: ^0.1.0
  lis3dh:
    url: github.com/nilwes/lis3dh
    version: ^2.1.0
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.0.0
  pixel_display:
    url: github.com/toitware/toit-pixel-display
    version: ^1.6.1
  solar_position:
    url: github.com/toitware/toit-solar-position
    version: ^0.0.3
  ssd1306:
    url: github.com/toitware/toit-ssd1306
    version: ^1.6.0
  telegram:
    url: github.com/floitsch/toit-telegram
    version: ^0.5.2
